"""
Seed data for commodities, materials, and cities.

This is a straight, field-renamed transcription of the arrays already
embedded in public/smartpack.html (COMMODITIES, MATERIALS, INDIA_CITIES) —
not a re-derivation. Every numeric value and its `source` string are
copied verbatim from there, so the frontend's offline fallback and the
database-backed API always agree, and every value keeps the provenance
it already had (USDA Agriculture Handbook 66, FDA CFSAN/LACF, BIS
standards, or "Estimate (author)" where no authoritative figure exists
-- see each commodity's source/ph_source and each material's source for
specifics). Do not add rows with invented numbers; extend this list only
with the same discipline -- a citable source or an explicit "Estimate
(author)" label.

Regenerating this file: it was produced by parsing smartpack.html's own
COMMODITIES/MATERIALS/INDIA_CITIES arrays and renaming JS camelCase/short
keys to the snake_case column names in app/models.py (see git history /
scripts/ if you need to redo this after the frontend's data changes).
"""
from __future__ import annotations

COMMODITIES: list[dict] = [{'name': 'Tomato',
  'category': 'produce',
  'moisture_pct': 94,
  'fat_pct': 0.2,
  'ph': 4.6,
  'ph_range': '4.30–4.90',
  'ph_source': 'FDA, Approximate pH of Foods and Food Products (CFSAN/LACF)',
  'water_activity': 0.99,
  'respiration_rate': 7.9,
  'o2_target_pct': 3,
  'co2_target_pct': 2,
  'base_shelf_life_days': 5,
  'source': 'USDA AH-66',
  'usda_temp_note': '13–21 °C to ripen; red fruit 7–13 °C briefly (chilling injury below 13 °C)',
  'usda_rh_note': '90–95%',
  'usda_life_note': 'days once red; weeks green',
  'respiration_curve': [[10, 7.9], [15, 11.9], [20, 19.4], [25, 24.6]]},
 {'name': 'Banana',
  'category': 'produce',
  'moisture_pct': 75,
  'fat_pct': 0.3,
  'ph': 4.85,
  'ph_range': '4.50–5.20',
  'ph_source': 'FDA, Approximate pH of Foods and Food Products (CFSAN/LACF)',
  'water_activity': 0.98,
  'respiration_rate': 42.1,
  'o2_target_pct': 4,
  'co2_target_pct': 5,
  'base_shelf_life_days': 6,
  'source': 'USDA AH-66',
  'usda_temp_note': '13–14 °C (green; chilling-sensitive below 13 °C)',
  'usda_rh_note': '90–95%',
  'usda_life_note': '7–28 days green, variety dependent',
  'respiration_curve': [[10, 42.1], [15, 75.7], [20, 155.6]]},
 {'name': 'Spinach',
  'category': 'produce',
  'moisture_pct': 91,
  'fat_pct': 0.4,
  'ph': 6.15,
  'ph_range': '5.50–6.80',
  'ph_source': 'FDA, Approximate pH of Foods and Food Products (CFSAN/LACF)',
  'water_activity': 0.99,
  'respiration_rate': 57.9,
  'o2_target_pct': 8,
  'co2_target_pct': 8,
  'base_shelf_life_days': 2,
  'source': 'USDA AH-66',
  'usda_temp_note': '0 °C',
  'usda_rh_note': '95–98%',
  'usda_life_note': '~2 weeks',
  'respiration_curve': [[0, 10.5], [5, 23.1], [10, 57.9], [15, 96.8], [20, 127.8]]},
 {'name': 'Strawberry',
  'category': 'produce',
  'moisture_pct': 90,
  'fat_pct': 0.3,
  'ph': 3.45,
  'ph_range': '3.00–3.90',
  'ph_source': 'FDA, Approximate pH of Foods and Food Products (CFSAN/LACF)',
  'water_activity': 0.98,
  'respiration_rate': 39.5,
  'o2_target_pct': 10,
  'co2_target_pct': 15,
  'base_shelf_life_days': 2,
  'source': 'USDA AH-66',
  'usda_temp_note': '0 °C',
  'usda_rh_note': '90–95%',
  'usda_life_note': 'up to 7 days',
  'respiration_curve': [[0, 8], [10, 39.5], [20, 83.3]]},
 {'name': 'Apple',
  'category': 'produce',
  'moisture_pct': 86,
  'fat_pct': 0.2,
  'ph': 3.65,
  'ph_range': '3.30–4.00',
  'ph_source': 'FDA, Approximate pH of Foods and Food Products (CFSAN/LACF) (apple, eating)',
  'water_activity': 0.97,
  'respiration_rate': 4.7,
  'o2_target_pct': 3,
  'co2_target_pct': 2.5,
  'base_shelf_life_days': 20,
  'source': 'USDA AH-66',
  'usda_temp_note': '−1 to 4 °C',
  'usda_rh_note': '90–95%',
  'usda_life_note': '3–8 months air storage (longer under CA)',
  'respiration_curve': [[0, 1.5], [5, 3.1], [10, 4.7], [15, 8.1], [20, 11.1]]},
 {'name': 'Potato',
  'category': 'produce',
  'moisture_pct': 79,
  'fat_pct': 0.1,
  'ph': 5.65,
  'ph_range': '5.40–5.90',
  'ph_source': 'FDA, Approximate pH of Foods and Food Products (CFSAN/LACF)',
  'water_activity': 0.98,
  'respiration_rate': 8.4,
  'o2_target_pct': 5,
  'co2_target_pct': 3,
  'base_shelf_life_days': 30,
  'source': 'USDA AH-66',
  'usda_temp_note': '7–10 °C fresh market (cured stock at 4–10 °C)',
  'usda_rh_note': '95–99%',
  'usda_life_note': '2–12 months cured',
  'respiration_curve': [[5, 6.2], [10, 8.4], [15, 9.2], [20, 12.2]]},
 {'name': 'Potato chips',
  'category': 'snack',
  'moisture_pct': 2,
  'fat_pct': 35,
  'ph': None,
  'ph_range': '—',
  'ph_source': 'No authoritative published value; shelf life of this product is controlled by '
               'water activity, not pH',
  'water_activity': 0.15,
  'respiration_rate': 0,
  'o2_target_pct': 0,
  'co2_target_pct': 0,
  'base_shelf_life_days': 90,
  'source': 'Estimate (author)',
  'usda_temp_note': None,
  'usda_rh_note': None,
  'usda_life_note': None,
  'respiration_curve': None},
 {'name': 'Biscuits',
  'category': 'bakery',
  'moisture_pct': 4,
  'fat_pct': 20,
  'ph': None,
  'ph_range': '3.5–8.0 (all bakery)',
  'ph_source': 'No authoritative single value; American Society of Baking gives 3.5–8.0 across '
               'bakery products',
  'water_activity': 0.25,
  'respiration_rate': 0,
  'o2_target_pct': 0,
  'co2_target_pct': 0,
  'base_shelf_life_days': 120,
  'source': 'Estimate (author)',
  'usda_temp_note': None,
  'usda_rh_note': None,
  'usda_life_note': None,
  'respiration_curve': None},
 {'name': 'Bread',
  'category': 'bakery',
  'moisture_pct': 35,
  'fat_pct': 3,
  'ph': 5.6,
  'ph_range': '5.00–6.20',
  'ph_source': 'FDA, Approximate pH of Foods and Food Products (CFSAN/LACF) (bread, white)',
  'water_activity': 0.96,
  'respiration_rate': 0,
  'o2_target_pct': 0,
  'co2_target_pct': 0,
  'base_shelf_life_days': 4,
  'source': 'Estimate (author)',
  'usda_temp_note': None,
  'usda_rh_note': None,
  'usda_life_note': None,
  'respiration_curve': None},
 {'name': 'Milk powder',
  'category': 'dairy',
  'moisture_pct': 3.5,
  'fat_pct': 26,
  'ph': 6.5,
  'ph_range': '—',
  'ph_source': 'USDA/ARS Pathogen Modeling Program, pH of Selected Foods (whole milk powder, '
               'reconstituted)',
  'water_activity': 0.2,
  'respiration_rate': 0,
  'o2_target_pct': 0,
  'co2_target_pct': 0,
  'base_shelf_life_days': 180,
  'source': 'Estimate (author)',
  'usda_temp_note': None,
  'usda_rh_note': None,
  'usda_life_note': None,
  'respiration_curve': None},
 {'name': 'Cheese',
  'category': 'dairy',
  'moisture_pct': 40,
  'fat_pct': 30,
  'ph': 5.9,
  'ph_range': '—',
  'ph_source': 'FDA, Approximate pH of Foods and Food Products (CFSAN/LACF) (cheese, Cheddar)',
  'water_activity': 0.95,
  'respiration_rate': 0,
  'o2_target_pct': 0,
  'co2_target_pct': 0,
  'base_shelf_life_days': 30,
  'source': 'Estimate (author)',
  'usda_temp_note': None,
  'usda_rh_note': None,
  'usda_life_note': None,
  'respiration_curve': None},
 {'name': 'Fresh chicken',
  'category': 'meat',
  'moisture_pct': 70,
  'fat_pct': 5,
  'ph': 5.85,
  'ph_range': '5.70–5.90',
  'ph_source': 'USDA/ARS Pathogen Modeling Program, pH of Selected Foods + Matarneh et al., '
               'Poultry Science (broiler pectoralis major ultimate pH)',
  'water_activity': 0.99,
  'respiration_rate': 0,
  'o2_target_pct': 0,
  'co2_target_pct': 0,
  'base_shelf_life_days': 1.5,
  'source': 'Estimate (author)',
  'usda_temp_note': None,
  'usda_rh_note': None,
  'usda_life_note': None,
  'respiration_curve': None},
 {'name': 'Frozen green peas',
  'category': 'frozen',
  'moisture_pct': 79,
  'fat_pct': 0.4,
  'ph': 6.55,
  'ph_range': '6.40–6.70',
  'ph_source': 'FDA, Approximate pH of Foods and Food Products (CFSAN/LACF) (peas, frozen)',
  'water_activity': 0.98,
  'respiration_rate': 0,
  'o2_target_pct': 0,
  'co2_target_pct': 0,
  'base_shelf_life_days': 3,
  'source': 'Estimate (author)',
  'usda_temp_note': None,
  'usda_rh_note': None,
  'usda_life_note': None,
  'respiration_curve': None},
 {'name': 'Chilli powder',
  'category': 'spice',
  'moisture_pct': 8,
  'fat_pct': 10,
  'ph': 4.95,
  'ph_range': '4.91–5.00',
  'ph_source': 'Rafi, Parween & Kishwer (2018), commercial red chilli powder study — indicative, '
               'no FDA/USDA standard value',
  'water_activity': 0.45,
  'respiration_rate': 0,
  'o2_target_pct': 0,
  'co2_target_pct': 0,
  'base_shelf_life_days': 120,
  'source': 'Estimate (author)',
  'usda_temp_note': None,
  'usda_rh_note': None,
  'usda_life_note': None,
  'respiration_curve': None}]

MATERIALS: list[dict] = [{'name': 'LDPE',
  'bis_standard': 'IS 10146 (food-grade PE)',
  'otr': 6500,
  'wvtr': 18,
  'thickness_um': 50,
  'cost_index': 1,
  'sustainability': 5,
  'strength': 5,
  'sealability': 9,
  'light_barrier': 3,
  'temp_min_c': -50,
  'temp_max_c': 80,
  'recyclable': 'Yes (#4)',
  'note': 'Cheap, heat-sealable, high gas permeability',
  'source': 'Estimate (author)'},
 {'name': 'HDPE',
  'bis_standard': 'IS 10146 (food-grade PE)',
  'otr': 1800,
  'wvtr': 7,
  'thickness_um': 40,
  'cost_index': 1.2,
  'sustainability': 6,
  'strength': 6,
  'sealability': 8,
  'light_barrier': 5,
  'temp_min_c': -50,
  'temp_max_c': 100,
  'recyclable': 'Yes (#2)',
  'note': 'Stiffer, better moisture barrier than LDPE',
  'source': 'Estimate (author)'},
 {'name': 'BOPP',
  'bis_standard': 'IS 10148 (food-grade PP)',
  'otr': 1500,
  'wvtr': 6,
  'thickness_um': 30,
  'cost_index': 1.5,
  'sustainability': 6,
  'strength': 7,
  'sealability': 7,
  'light_barrier': 2,
  'temp_min_c': -20,
  'temp_max_c': 100,
  'recyclable': 'Yes (#5)',
  'note': 'Clear, good moisture barrier, printable',
  'source': 'Estimate (author)'},
 {'name': 'PET',
  'bis_standard': 'IS 12252 (food-grade PET)',
  'otr': 100,
  'wvtr': 40,
  'thickness_um': 12,
  'cost_index': 2,
  'sustainability': 6,
  'strength': 9,
  'sealability': 3,
  'light_barrier': 2,
  'temp_min_c': -40,
  'temp_max_c': 150,
  'recyclable': 'Yes (#1)',
  'note': 'Strong, good gas barrier; needs a sealant layer',
  'source': 'Estimate (author)'},
 {'name': 'PET/LDPE laminate',
  'bis_standard': 'IS 16034 (multilayer laminate)',
  'otr': 90,
  'wvtr': 15,
  'thickness_um': 62,
  'cost_index': 2.5,
  'sustainability': 4,
  'strength': 8,
  'sealability': 9,
  'light_barrier': 2,
  'temp_min_c': -40,
  'temp_max_c': 80,
  'recyclable': 'Limited',
  'note': 'Sealable barrier laminate',
  'source': 'Estimate (author)'},
 {'name': 'Metallized PET/PE',
  'bis_standard': 'IS 16034 (multilayer laminate)',
  'otr': 0.77,
  'wvtr': 1,
  'thickness_um': 60,
  'cost_index': 3,
  'sustainability': 3,
  'strength': 8,
  'sealability': 9,
  'light_barrier': 9,
  'temp_min_c': -40,
  'temp_max_c': 80,
  'recyclable': 'No',
  'note': 'High barrier for snacks, powders, coffee',
  'source': 'Piergiovanni & Limbo 2016, Table 6.3 (29 nm Al on 25 µm PET)'},
 {'name': 'Aluminium foil laminate',
  'bis_standard': 'IS 16034 (multilayer laminate)',
  'otr': 0.05,
  'wvtr': 0.05,
  'thickness_um': 80,
  'cost_index': 4.5,
  'sustainability': 2,
  'strength': 7,
  'sealability': 8,
  'light_barrier': 10,
  'temp_min_c': -40,
  'temp_max_c': 120,
  'recyclable': 'No',
  'note': 'Absolute barrier, retort/long shelf life',
  'source': 'Estimate (author)'},
 {'name': 'EVOH coextrusion',
  'bis_standard': 'IS 16034 (multilayer laminate)',
  'otr': 3,
  'wvtr': 8,
  'thickness_um': 70,
  'cost_index': 3.5,
  'sustainability': 4,
  'strength': 8,
  'sealability': 9,
  'light_barrier': 3,
  'temp_min_c': -40,
  'temp_max_c': 80,
  'recyclable': 'Limited',
  'note': 'Excellent O2 barrier for MAP meat and cheese',
  'source': 'Estimate (author)'},
 {'name': 'PLA (biodegradable)',
  'bis_standard': 'IS/ISO 17088 (compostable)',
  'otr': 800,
  'wvtr': 100,
  'thickness_um': 30,
  'cost_index': 3,
  'sustainability': 8,
  'strength': 5,
  'sealability': 6,
  'light_barrier': 2,
  'temp_min_c': -10,
  'temp_max_c': 50,
  'recyclable': 'Compostable',
  'note': 'Bio-based; poor heat resistance and moisture barrier',
  'source': 'Estimate (author)'},
 {'name': 'Micro-perforated BOPP',
  'bis_standard': 'IS 10148 (food-grade PP)',
  'otr': 12000,
  'wvtr': 30,
  'thickness_um': 30,
  'cost_index': 2,
  'sustainability': 5,
  'strength': 7,
  'sealability': 7,
  'light_barrier': 2,
  'temp_min_c': -20,
  'temp_max_c': 80,
  'recyclable': 'Yes (#5)',
  'note': 'Breathable; perforation count tunes OTR for produce',
  'source': 'Estimate (author)'},
 {'name': 'Cast PP (CPP)',
  'bis_standard': 'IS 10148 (food-grade PP)',
  'otr': 1800,
  'wvtr': 6,
  'thickness_um': 35,
  'cost_index': 1.4,
  'sustainability': 5,
  'strength': 6,
  'sealability': 9,
  'light_barrier': 2,
  'temp_min_c': -20,
  'temp_max_c': 120,
  'recyclable': 'Yes (#5)',
  'note': 'Common heat-seal layer in laminates; good clarity',
  'source': 'Estimate (author)'},
 {'name': 'Rigid PVC',
  'bis_standard': 'IS 10151 (food-grade PVC)',
  'otr': 250,
  'wvtr': 25,
  'thickness_um': 300,
  'cost_index': 2,
  'sustainability': 3,
  'strength': 7,
  'sealability': 4,
  'light_barrier': 3,
  'temp_min_c': -10,
  'temp_max_c': 60,
  'recyclable': 'Yes (#3)',
  'note': 'Clear rigid trays and blisters; moderate O2 barrier',
  'source': 'Estimate (author)'},
 {'name': 'PVDC-coated film',
  'bis_standard': 'IS 16034 (multilayer laminate)',
  'otr': 15,
  'wvtr': 3,
  'thickness_um': 30,
  'cost_index': 2.8,
  'sustainability': 3,
  'strength': 6,
  'sealability': 7,
  'light_barrier': 3,
  'temp_min_c': -20,
  'temp_max_c': 90,
  'recyclable': 'No',
  'note': 'High-barrier coating on OPP/PA; chlorine content limits recycling',
  'source': 'Estimate (author)'},
 {'name': 'Polystyrene (GPPS)',
  'bis_standard': 'IS 10142 (food-grade PS)',
  'otr': 5000,
  'wvtr': 120,
  'thickness_um': 500,
  'cost_index': 1.5,
  'sustainability': 4,
  'strength': 4,
  'sealability': 3,
  'light_barrier': 3,
  'temp_min_c': -20,
  'temp_max_c': 70,
  'recyclable': 'Yes (#6)',
  'note': 'Clear rigid cups and trays; brittle',
  'source': 'Estimate (author)'},
 {'name': 'Expanded polystyrene (EPS)',
  'bis_standard': 'IS 10142 (food-grade PS)',
  'otr': 20000,
  'wvtr': 150,
  'thickness_um': 2000,
  'cost_index': 1,
  'sustainability': 2,
  'strength': 3,
  'sealability': 2,
  'light_barrier': 7,
  'temp_min_c': -40,
  'temp_max_c': 80,
  'recyclable': 'Limited',
  'note': 'Insulating produce/meat trays; bulky to recycle',
  'source': 'Estimate (author)'},
 {'name': 'Biaxially oriented nylon (BOPA)',
  'bis_standard': 'IS 16034 (PA laminate use)',
  'otr': 40,
  'wvtr': 250,
  'thickness_um': 15,
  'cost_index': 3,
  'sustainability': 5,
  'strength': 9,
  'sealability': 4,
  'light_barrier': 2,
  'temp_min_c': -60,
  'temp_max_c': 150,
  'recyclable': 'Limited',
  'note': 'Excellent puncture and O2 barrier; poor moisture barrier alone',
  'source': 'Estimate (author)'},
 {'name': 'PA/PE laminate',
  'bis_standard': 'IS 16034 (multilayer laminate)',
  'otr': 40,
  'wvtr': 15,
  'thickness_um': 70,
  'cost_index': 3,
  'sustainability': 4,
  'strength': 8,
  'sealability': 9,
  'light_barrier': 3,
  'temp_min_c': -40,
  'temp_max_c': 90,
  'recyclable': 'Limited',
  'note': 'Vacuum meat/cheese packs; nylon strength with PE seal layer',
  'source': 'Estimate (author)'},
 {'name': 'Ionomer (Surlyn-type)',
  'bis_standard': 'IS 16034 (multilayer laminate)',
  'otr': 3000,
  'wvtr': 15,
  'thickness_um': 50,
  'cost_index': 3.2,
  'sustainability': 4,
  'strength': 7,
  'sealability': 10,
  'light_barrier': 2,
  'temp_min_c': -70,
  'temp_max_c': 90,
  'recyclable': 'Limited',
  'note': 'Outstanding hot-tack seal; usually the innermost sealant layer',
  'source': 'Estimate (author)'},
 {'name': 'Cellophane (uncoated)',
  'bis_standard': 'IS 4600 (cellulose film)',
  'otr': 10,
  'wvtr': 600,
  'thickness_um': 30,
  'cost_index': 2,
  'sustainability': 8,
  'strength': 5,
  'sealability': 2,
  'light_barrier': 1,
  'temp_min_c': -20,
  'temp_max_c': 150,
  'recyclable': 'Compostable',
  'note': 'Regenerated cellulose; biodegradable but very poor moisture barrier',
  'source': 'Estimate (author)'},
 {'name': 'Glassine paper',
  'bis_standard': 'IS 10106 (paper-based)',
  'otr': 2000,
  'wvtr': 250,
  'thickness_um': 40,
  'cost_index': 1.5,
  'sustainability': 7,
  'strength': 3,
  'sealability': 1,
  'light_barrier': 5,
  'temp_min_c': -20,
  'temp_max_c': 150,
  'recyclable': 'Yes (paper)',
  'note': 'Greaseproof paper for bakery and confectionery wraps',
  'source': 'Estimate (author)'},
 {'name': 'Kraft paper',
  'bis_standard': 'IS 10106 (paper-based)',
  'otr': 15000,
  'wvtr': 1000,
  'thickness_um': 80,
  'cost_index': 1,
  'sustainability': 8,
  'strength': 4,
  'sealability': 1,
  'light_barrier': 8,
  'temp_min_c': -20,
  'temp_max_c': 150,
  'recyclable': 'Yes (paper)',
  'note': 'Cheap and breathable; essentially no gas or moisture barrier alone',
  'source': 'Estimate (author)'},
 {'name': 'Wax-coated paper',
  'bis_standard': 'IS 10106 (paper-based)',
  'otr': 3000,
  'wvtr': 15,
  'thickness_um': 60,
  'cost_index': 1.4,
  'sustainability': 6,
  'strength': 3,
  'sealability': 4,
  'light_barrier': 6,
  'temp_min_c': -10,
  'temp_max_c': 40,
  'recyclable': 'Limited',
  'note': 'Traditional produce wrap; coating softens above ~40 °C',
  'source': 'Estimate (author)'},
 {'name': 'LDPE-coated paperboard',
  'bis_standard': 'IS 10106 (paper-based)',
  'otr': 5000,
  'wvtr': 10,
  'thickness_um': 350,
  'cost_index': 2,
  'sustainability': 6,
  'strength': 7,
  'sealability': 8,
  'light_barrier': 8,
  'temp_min_c': -20,
  'temp_max_c': 80,
  'recyclable': 'Limited',
  'note': 'Liquid cartons: paperboard stiffness with a PE liquid barrier',
  'source': 'Estimate (author)'},
 {'name': 'Corrugated fibreboard',
  'bis_standard': 'IS 2771 (corrugated boxes)',
  'otr': 30000,
  'wvtr': 2000,
  'thickness_um': 3000,
  'cost_index': 1.2,
  'sustainability': 9,
  'strength': 9,
  'sealability': 1,
  'light_barrier': 9,
  'temp_min_c': -30,
  'temp_max_c': 60,
  'recyclable': 'Yes (paper)',
  'note': 'Outer shipping case; not a barrier layer on its own',
  'source': 'Estimate (author)'},
 {'name': 'HDPE woven sack (raffia)',
  'bis_standard': 'IS 14887 (woven sacks)',
  'otr': 20000,
  'wvtr': 50,
  'thickness_um': 200,
  'cost_index': 1,
  'sustainability': 5,
  'strength': 8,
  'sealability': 3,
  'light_barrier': 6,
  'temp_min_c': -30,
  'temp_max_c': 80,
  'recyclable': 'Yes (#2)',
  'note': 'Bulk grain/sugar sacks; needs a PE liner for any real barrier',
  'source': 'Estimate (author)'},
 {'name': 'LDPE-coated jute bag',
  'bis_standard': 'IS 10106 (lined sacks)',
  'otr': 25000,
  'wvtr': 40,
  'thickness_um': 500,
  'cost_index': 1.3,
  'sustainability': 9,
  'strength': 7,
  'sealability': 2,
  'light_barrier': 7,
  'temp_min_c': -20,
  'temp_max_c': 80,
  'recyclable': 'Limited',
  'note': 'Natural-fibre sack with a thin PE moisture liner',
  'source': 'Estimate (author)'},
 {'name': 'PET bottle (blow-moulded)',
  'bis_standard': 'IS 13193 (PET bottles)',
  'otr': 20,
  'wvtr': 2,
  'thickness_um': 300,
  'cost_index': 2.2,
  'sustainability': 6,
  'strength': 9,
  'sealability': 5,
  'light_barrier': 2,
  'temp_min_c': -20,
  'temp_max_c': 60,
  'recyclable': 'Yes (#1)',
  'note': 'Water and carbonated drinks; barrier scales with wall thickness, needs a closure',
  'source': 'Estimate (author)'},
 {'name': 'HDPE bottle',
  'bis_standard': 'IS 10146 (food-grade PE)',
  'otr': 50,
  'wvtr': 1,
  'thickness_um': 500,
  'cost_index': 1.8,
  'sustainability': 6,
  'strength': 8,
  'sealability': 5,
  'light_barrier': 6,
  'temp_min_c': -40,
  'temp_max_c': 80,
  'recyclable': 'Yes (#2)',
  'note': 'Milk jugs and similar rigid bottles',
  'source': 'Estimate (author)'},
 {'name': 'Retort pouch (PET/Al/CPP)',
  'bis_standard': 'IS 16034 (retort laminate)',
  'otr': 0.05,
  'wvtr': 0.1,
  'thickness_um': 100,
  'cost_index': 4,
  'sustainability': 2,
  'strength': 9,
  'sealability': 9,
  'light_barrier': 10,
  'temp_min_c': -40,
  'temp_max_c': 135,
  'recyclable': 'No',
  'note': 'Withstands retort sterilisation (~121 °C); shelf-stable ready meals',
  'source': 'Estimate (author)'},
 {'name': 'Aseptic carton (paper/Al/PE)',
  'bis_standard': 'IS 16034 (aseptic laminate)',
  'otr': 0.5,
  'wvtr': 0.3,
  'thickness_um': 380,
  'cost_index': 3.5,
  'sustainability': 6,
  'strength': 8,
  'sealability': 8,
  'light_barrier': 9,
  'temp_min_c': -20,
  'temp_max_c': 60,
  'recyclable': 'Limited',
  'note': 'Long-life liquid cartons; mostly paper by weight (Tetra Pak-style)',
  'source': 'Estimate (author)'},
 {'name': 'Tinplate can',
  'bis_standard': 'IS 1993 (tinplate)',
  'otr': 0.01,
  'wvtr': 0.01,
  'thickness_um': 200,
  'cost_index': 3.5,
  'sustainability': 6,
  'strength': 10,
  'sealability': 10,
  'light_barrier': 10,
  'temp_min_c': -40,
  'temp_max_c': 180,
  'recyclable': 'Yes (steel)',
  'note': 'Near-absolute barrier, retort-stable canning material',
  'source': 'Estimate (author)'},
 {'name': 'Aluminium can/tray',
  'bis_standard': 'IS 14407 (aluminium)',
  'otr': 0,
  'wvtr': 0,
  'thickness_um': 150,
  'cost_index': 3.8,
  'sustainability': 5,
  'strength': 9,
  'sealability': 8,
  'light_barrier': 10,
  'temp_min_c': -40,
  'temp_max_c': 200,
  'recyclable': 'Yes (aluminium)',
  'note': 'Infinitely recyclable, absolute barrier',
  'source': 'Estimate (author)'},
 {'name': 'Glass container',
  'bis_standard': 'IS 13926 (glass containers)',
  'otr': 0,
  'wvtr': 0,
  'thickness_um': 2500,
  'cost_index': 2.5,
  'sustainability': 7,
  'strength': 9,
  'sealability': 9,
  'light_barrier': 2,
  'temp_min_c': -40,
  'temp_max_c': 300,
  'recyclable': 'Yes (glass)',
  'note': 'Inert and infinitely recyclable; heavy and fragile',
  'source': 'Estimate (author)'},
 {'name': 'PHA/PHB bioplastic',
  'bis_standard': 'IS/ISO 17088 (compostable)',
  'otr': 15,
  'wvtr': 20,
  'thickness_um': 40,
  'cost_index': 4.5,
  'sustainability': 9,
  'strength': 6,
  'sealability': 6,
  'light_barrier': 3,
  'temp_min_c': -10,
  'temp_max_c': 60,
  'recyclable': 'Compostable',
  'note': 'Marine-degradable bioplastic, PP-like barrier, still costly',
  'source': 'Estimate (author)'},
 {'name': 'Starch-blend bioplastic',
  'bis_standard': 'IS/ISO 17088 (compostable)',
  'otr': 500,
  'wvtr': 150,
  'thickness_um': 30,
  'cost_index': 3,
  'sustainability': 8,
  'strength': 4,
  'sealability': 6,
  'light_barrier': 4,
  'temp_min_c': -10,
  'temp_max_c': 45,
  'recyclable': 'Compostable',
  'note': 'Home-compostable carrier bags; weak moisture barrier',
  'source': 'Estimate (author)'},
 {'name': 'Shrink film (PVC/POF)',
  'bis_standard': 'IS 16034 (multilayer laminate)',
  'otr': 2000,
  'wvtr': 15,
  'thickness_um': 20,
  'cost_index': 1.6,
  'sustainability': 4,
  'strength': 5,
  'sealability': 6,
  'light_barrier': 2,
  'temp_min_c': -10,
  'temp_max_c': 70,
  'recyclable': 'Limited',
  'note': 'Bundling/overwrap; not a primary barrier layer',
  'source': 'Estimate (author)'},
 {'name': 'Skin-pack film (EVA/ionomer)',
  'bis_standard': 'IS 16034 (multilayer laminate)',
  'otr': 800,
  'wvtr': 20,
  'thickness_um': 40,
  'cost_index': 2.5,
  'sustainability': 4,
  'strength': 6,
  'sealability': 9,
  'light_barrier': 2,
  'temp_min_c': -20,
  'temp_max_c': 80,
  'recyclable': 'Limited',
  'note': 'Vacuum skin packaging conforms tightly to product surface',
  'source': 'Estimate (author)'},
 {'name': 'Medium-density PE (MDPE)',
  'bis_standard': 'IS 10146 (food-grade PE)',
  'otr': 4000,
  'wvtr': 10,
  'thickness_um': 45,
  'cost_index': 1.1,
  'sustainability': 5,
  'strength': 6,
  'sealability': 8,
  'light_barrier': 3,
  'temp_min_c': -40,
  'temp_max_c': 90,
  'recyclable': 'Yes (#4)',
  'note': 'Carrier bags; stiffer than LDPE, more flexible than HDPE',
  'source': 'Estimate (author)'}]

CITIES: list[dict] = [{'state': 'Maharashtra',
  'city': 'Mumbai',
  'lat': 19.076,
  'lon': 72.877,
  'peak_temp_c': 33,
  'peak_rh_pct': 80,
  'climate_note': 'Coastal, hot & humid'},
 {'state': 'Maharashtra',
  'city': 'Pune',
  'lat': 18.52,
  'lon': 73.856,
  'peak_temp_c': 32,
  'peak_rh_pct': 55,
  'climate_note': 'Moderate, drier inland'},
 {'state': 'Maharashtra',
  'city': 'Nagpur',
  'lat': 21.146,
  'lon': 79.089,
  'peak_temp_c': 44,
  'peak_rh_pct': 35,
  'climate_note': 'Very hot, dry summer'},
 {'state': 'Maharashtra',
  'city': 'Nashik',
  'lat': 19.998,
  'lon': 73.791,
  'peak_temp_c': 35,
  'peak_rh_pct': 50,
  'climate_note': 'Warm, moderate humidity'},
 {'state': 'Delhi',
  'city': 'New Delhi',
  'lat': 28.613,
  'lon': 77.209,
  'peak_temp_c': 42,
  'peak_rh_pct': 30,
  'climate_note': 'Hot & dry summers'},
 {'state': 'West Bengal',
  'city': 'Kolkata',
  'lat': 22.572,
  'lon': 88.363,
  'peak_temp_c': 35,
  'peak_rh_pct': 85,
  'climate_note': 'Hot & very humid'},
 {'state': 'West Bengal',
  'city': 'Siliguri',
  'lat': 26.727,
  'lon': 88.396,
  'peak_temp_c': 33,
  'peak_rh_pct': 80,
  'climate_note': 'Humid, foothill climate'},
 {'state': 'West Bengal',
  'city': 'Durgapur',
  'lat': 23.52,
  'lon': 87.311,
  'peak_temp_c': 38,
  'peak_rh_pct': 65,
  'climate_note': 'Hot, industrial belt'},
 {'state': 'Tamil Nadu',
  'city': 'Chennai',
  'lat': 13.082,
  'lon': 80.27,
  'peak_temp_c': 38,
  'peak_rh_pct': 75,
  'climate_note': 'Coastal, hot & humid'},
 {'state': 'Tamil Nadu',
  'city': 'Coimbatore',
  'lat': 11.017,
  'lon': 76.956,
  'peak_temp_c': 33,
  'peak_rh_pct': 55,
  'climate_note': 'Warm, drier inland'},
 {'state': 'Tamil Nadu',
  'city': 'Madurai',
  'lat': 9.925,
  'lon': 78.12,
  'peak_temp_c': 38,
  'peak_rh_pct': 55,
  'climate_note': 'Hot, semi-arid'},
 {'state': 'Tamil Nadu',
  'city': 'Tiruchirappalli',
  'lat': 10.79,
  'lon': 78.704,
  'peak_temp_c': 39,
  'peak_rh_pct': 55,
  'climate_note': 'Very hot, moderate humidity'},
 {'state': 'Karnataka',
  'city': 'Bengaluru',
  'lat': 12.971,
  'lon': 77.594,
  'peak_temp_c': 30,
  'peak_rh_pct': 60,
  'climate_note': 'Mild, moderate humidity'},
 {'state': 'Karnataka',
  'city': 'Mysuru',
  'lat': 12.295,
  'lon': 76.639,
  'peak_temp_c': 32,
  'peak_rh_pct': 55,
  'climate_note': 'Warm, moderate humidity'},
 {'state': 'Karnataka',
  'city': 'Hubballi',
  'lat': 15.364,
  'lon': 75.124,
  'peak_temp_c': 35,
  'peak_rh_pct': 50,
  'climate_note': 'Hot, semi-arid'},
 {'state': 'Karnataka',
  'city': 'Mangaluru',
  'lat': 12.914,
  'lon': 74.856,
  'peak_temp_c': 33,
  'peak_rh_pct': 80,
  'climate_note': 'Coastal, humid'},
 {'state': 'Telangana',
  'city': 'Hyderabad',
  'lat': 17.385,
  'lon': 78.486,
  'peak_temp_c': 38,
  'peak_rh_pct': 50,
  'climate_note': 'Hot, semi-arid'},
 {'state': 'Telangana',
  'city': 'Warangal',
  'lat': 17.978,
  'lon': 79.594,
  'peak_temp_c': 40,
  'peak_rh_pct': 45,
  'climate_note': 'Very hot, dry'},
 {'state': 'Gujarat',
  'city': 'Ahmedabad',
  'lat': 23.022,
  'lon': 72.571,
  'peak_temp_c': 42,
  'peak_rh_pct': 40,
  'climate_note': 'Hot & dry'},
 {'state': 'Gujarat',
  'city': 'Surat',
  'lat': 21.17,
  'lon': 72.831,
  'peak_temp_c': 37,
  'peak_rh_pct': 70,
  'climate_note': 'Warm, humid coastal belt'},
 {'state': 'Gujarat',
  'city': 'Vadodara',
  'lat': 22.307,
  'lon': 73.181,
  'peak_temp_c': 40,
  'peak_rh_pct': 55,
  'climate_note': 'Hot, moderate humidity'},
 {'state': 'Gujarat',
  'city': 'Rajkot',
  'lat': 22.303,
  'lon': 70.802,
  'peak_temp_c': 41,
  'peak_rh_pct': 40,
  'climate_note': 'Hot & dry'},
 {'state': 'Rajasthan',
  'city': 'Jaipur',
  'lat': 26.912,
  'lon': 75.787,
  'peak_temp_c': 42,
  'peak_rh_pct': 30,
  'climate_note': 'Desert, hot & very dry'},
 {'state': 'Rajasthan',
  'city': 'Jodhpur',
  'lat': 26.238,
  'lon': 73.024,
  'peak_temp_c': 44,
  'peak_rh_pct': 25,
  'climate_note': 'Desert, very hot & very dry'},
 {'state': 'Rajasthan',
  'city': 'Udaipur',
  'lat': 24.585,
  'lon': 73.712,
  'peak_temp_c': 38,
  'peak_rh_pct': 35,
  'climate_note': 'Hot, drier lake-city climate'},
 {'state': 'Rajasthan',
  'city': 'Kota',
  'lat': 25.213,
  'lon': 75.865,
  'peak_temp_c': 43,
  'peak_rh_pct': 30,
  'climate_note': 'Very hot, dry'},
 {'state': 'Punjab',
  'city': 'Amritsar',
  'lat': 31.634,
  'lon': 74.872,
  'peak_temp_c': 40,
  'peak_rh_pct': 45,
  'climate_note': 'Hot summer, cold winter'},
 {'state': 'Punjab',
  'city': 'Ludhiana',
  'lat': 30.901,
  'lon': 75.857,
  'peak_temp_c': 41,
  'peak_rh_pct': 45,
  'climate_note': 'Hot summer, cold winter'},
 {'state': 'Punjab',
  'city': 'Jalandhar',
  'lat': 31.326,
  'lon': 75.576,
  'peak_temp_c': 40,
  'peak_rh_pct': 45,
  'climate_note': 'Hot summer, cold winter'},
 {'state': 'Uttar Pradesh',
  'city': 'Lucknow',
  'lat': 26.847,
  'lon': 80.947,
  'peak_temp_c': 40,
  'peak_rh_pct': 40,
  'climate_note': 'Hot & dry summer'},
 {'state': 'Uttar Pradesh',
  'city': 'Kanpur',
  'lat': 26.449,
  'lon': 80.332,
  'peak_temp_c': 42,
  'peak_rh_pct': 40,
  'climate_note': 'Very hot & dry summer'},
 {'state': 'Uttar Pradesh',
  'city': 'Varanasi',
  'lat': 25.317,
  'lon': 82.973,
  'peak_temp_c': 41,
  'peak_rh_pct': 55,
  'climate_note': 'Hot & humid summer'},
 {'state': 'Uttar Pradesh',
  'city': 'Agra',
  'lat': 27.176,
  'lon': 78.008,
  'peak_temp_c': 43,
  'peak_rh_pct': 35,
  'climate_note': 'Very hot & dry'},
 {'state': 'Uttar Pradesh',
  'city': 'Noida',
  'lat': 28.535,
  'lon': 77.391,
  'peak_temp_c': 41,
  'peak_rh_pct': 40,
  'climate_note': 'Hot & dry, NCR belt'},
 {'state': 'Kerala',
  'city': 'Kochi',
  'lat': 9.931,
  'lon': 76.267,
  'peak_temp_c': 32,
  'peak_rh_pct': 85,
  'climate_note': 'Tropical, very humid'},
 {'state': 'Kerala',
  'city': 'Thiruvananthapuram',
  'lat': 8.524,
  'lon': 76.936,
  'peak_temp_c': 33,
  'peak_rh_pct': 80,
  'climate_note': 'Tropical, humid coastal'},
 {'state': 'Kerala',
  'city': 'Kozhikode',
  'lat': 11.258,
  'lon': 75.78,
  'peak_temp_c': 32,
  'peak_rh_pct': 82,
  'climate_note': 'Tropical, very humid'},
 {'state': 'Assam',
  'city': 'Guwahati',
  'lat': 26.144,
  'lon': 91.736,
  'peak_temp_c': 33,
  'peak_rh_pct': 85,
  'climate_note': 'Humid, high rainfall'},
 {'state': 'Assam',
  'city': 'Dibrugarh',
  'lat': 27.483,
  'lon': 94.912,
  'peak_temp_c': 32,
  'peak_rh_pct': 85,
  'climate_note': 'Humid, high rainfall'},
 {'state': 'Jammu & Kashmir',
  'city': 'Srinagar',
  'lat': 34.083,
  'lon': 74.797,
  'peak_temp_c': 30,
  'peak_rh_pct': 50,
  'climate_note': 'Cool mountain climate'},
 {'state': 'Jammu & Kashmir',
  'city': 'Jammu',
  'lat': 32.727,
  'lon': 74.857,
  'peak_temp_c': 40,
  'peak_rh_pct': 45,
  'climate_note': 'Hot summer, foothill climate'},
 {'state': 'Himachal Pradesh',
  'city': 'Shimla',
  'lat': 31.104,
  'lon': 77.173,
  'peak_temp_c': 25,
  'peak_rh_pct': 55,
  'climate_note': 'Cool hill climate'},
 {'state': 'Himachal Pradesh',
  'city': 'Dharamshala',
  'lat': 32.219,
  'lon': 76.323,
  'peak_temp_c': 28,
  'peak_rh_pct': 60,
  'climate_note': 'Cool, humid hill climate'},
 {'state': 'Madhya Pradesh',
  'city': 'Bhopal',
  'lat': 23.259,
  'lon': 77.412,
  'peak_temp_c': 40,
  'peak_rh_pct': 45,
  'climate_note': 'Hot, central India'},
 {'state': 'Madhya Pradesh',
  'city': 'Indore',
  'lat': 22.719,
  'lon': 75.858,
  'peak_temp_c': 39,
  'peak_rh_pct': 45,
  'climate_note': 'Hot, moderate humidity'},
 {'state': 'Madhya Pradesh',
  'city': 'Jabalpur',
  'lat': 23.181,
  'lon': 79.986,
  'peak_temp_c': 41,
  'peak_rh_pct': 50,
  'climate_note': 'Very hot, central India'},
 {'state': 'Madhya Pradesh',
  'city': 'Gwalior',
  'lat': 26.218,
  'lon': 78.183,
  'peak_temp_c': 43,
  'peak_rh_pct': 35,
  'climate_note': 'Very hot & dry'},
 {'state': 'Bihar',
  'city': 'Patna',
  'lat': 25.594,
  'lon': 85.137,
  'peak_temp_c': 40,
  'peak_rh_pct': 70,
  'climate_note': 'Hot & humid'},
 {'state': 'Bihar',
  'city': 'Gaya',
  'lat': 24.796,
  'lon': 85.0,
  'peak_temp_c': 41,
  'peak_rh_pct': 60,
  'climate_note': 'Very hot, moderate humidity'},
 {'state': 'Odisha',
  'city': 'Bhubaneswar',
  'lat': 20.296,
  'lon': 85.824,
  'peak_temp_c': 38,
  'peak_rh_pct': 80,
  'climate_note': 'Coastal, hot & humid'},
 {'state': 'Odisha',
  'city': 'Cuttack',
  'lat': 20.462,
  'lon': 85.879,
  'peak_temp_c': 38,
  'peak_rh_pct': 80,
  'climate_note': 'Coastal, hot & humid'},
 {'state': 'Odisha',
  'city': 'Rourkela',
  'lat': 22.227,
  'lon': 84.857,
  'peak_temp_c': 40,
  'peak_rh_pct': 60,
  'climate_note': 'Very hot, industrial belt'},
 {'state': 'Andhra Pradesh',
  'city': 'Visakhapatnam',
  'lat': 17.686,
  'lon': 83.218,
  'peak_temp_c': 35,
  'peak_rh_pct': 75,
  'climate_note': 'Coastal, hot & humid'},
 {'state': 'Andhra Pradesh',
  'city': 'Vijayawada',
  'lat': 16.507,
  'lon': 80.648,
  'peak_temp_c': 40,
  'peak_rh_pct': 60,
  'climate_note': 'Very hot, humid'},
 {'state': 'Andhra Pradesh',
  'city': 'Tirupati',
  'lat': 13.63,
  'lon': 79.42,
  'peak_temp_c': 37,
  'peak_rh_pct': 60,
  'climate_note': 'Hot, moderate humidity'},
 {'state': 'Goa',
  'city': 'Panaji',
  'lat': 15.49,
  'lon': 73.827,
  'peak_temp_c': 32,
  'peak_rh_pct': 85,
  'climate_note': 'Coastal, very humid'},
 {'state': 'Goa',
  'city': 'Margao',
  'lat': 15.273,
  'lon': 73.958,
  'peak_temp_c': 32,
  'peak_rh_pct': 85,
  'climate_note': 'Coastal, very humid'},
 {'state': 'Haryana',
  'city': 'Gurugram',
  'lat': 28.459,
  'lon': 77.026,
  'peak_temp_c': 42,
  'peak_rh_pct': 35,
  'climate_note': 'Hot & dry, NCR belt'},
 {'state': 'Haryana',
  'city': 'Faridabad',
  'lat': 28.408,
  'lon': 77.317,
  'peak_temp_c': 42,
  'peak_rh_pct': 35,
  'climate_note': 'Hot & dry, NCR belt'},
 {'state': 'Haryana',
  'city': 'Panipat',
  'lat': 29.39,
  'lon': 76.996,
  'peak_temp_c': 41,
  'peak_rh_pct': 35,
  'climate_note': 'Hot summer, cold winter'},
 {'state': 'Chhattisgarh',
  'city': 'Raipur',
  'lat': 21.251,
  'lon': 81.629,
  'peak_temp_c': 42,
  'peak_rh_pct': 50,
  'climate_note': 'Very hot, central India'},
 {'state': 'Chhattisgarh',
  'city': 'Bhilai',
  'lat': 21.209,
  'lon': 81.428,
  'peak_temp_c': 42,
  'peak_rh_pct': 50,
  'climate_note': 'Very hot, industrial belt'},
 {'state': 'Jharkhand',
  'city': 'Ranchi',
  'lat': 23.344,
  'lon': 85.309,
  'peak_temp_c': 36,
  'peak_rh_pct': 60,
  'climate_note': 'Warm, plateau climate'},
 {'state': 'Jharkhand',
  'city': 'Jamshedpur',
  'lat': 22.804,
  'lon': 86.185,
  'peak_temp_c': 38,
  'peak_rh_pct': 65,
  'climate_note': 'Hot, industrial belt'},
 {'state': 'Jharkhand',
  'city': 'Dhanbad',
  'lat': 23.795,
  'lon': 86.43,
  'peak_temp_c': 38,
  'peak_rh_pct': 60,
  'climate_note': 'Hot, coal-belt climate'},
 {'state': 'Uttarakhand',
  'city': 'Dehradun',
  'lat': 30.317,
  'lon': 78.032,
  'peak_temp_c': 35,
  'peak_rh_pct': 55,
  'climate_note': 'Warm valley, cool winters'},
 {'state': 'Uttarakhand',
  'city': 'Haridwar',
  'lat': 29.945,
  'lon': 78.164,
  'peak_temp_c': 38,
  'peak_rh_pct': 55,
  'climate_note': 'Hot summer, foothill climate'},
 {'state': 'Tripura',
  'city': 'Agartala',
  'lat': 23.837,
  'lon': 91.279,
  'peak_temp_c': 34,
  'peak_rh_pct': 85,
  'climate_note': 'Humid, high rainfall'},
 {'state': 'Meghalaya',
  'city': 'Shillong',
  'lat': 25.578,
  'lon': 91.893,
  'peak_temp_c': 26,
  'peak_rh_pct': 80,
  'climate_note': 'Cool, very humid hill climate'},
 {'state': 'Manipur',
  'city': 'Imphal',
  'lat': 24.817,
  'lon': 93.937,
  'peak_temp_c': 31,
  'peak_rh_pct': 75,
  'climate_note': 'Mild, humid valley climate'},
 {'state': 'Nagaland',
  'city': 'Kohima',
  'lat': 25.674,
  'lon': 94.11,
  'peak_temp_c': 27,
  'peak_rh_pct': 75,
  'climate_note': 'Cool, humid hill climate'},
 {'state': 'Mizoram',
  'city': 'Aizawl',
  'lat': 23.727,
  'lon': 92.717,
  'peak_temp_c': 28,
  'peak_rh_pct': 80,
  'climate_note': 'Cool, humid hill climate'},
 {'state': 'Arunachal Pradesh',
  'city': 'Itanagar',
  'lat': 27.084,
  'lon': 93.605,
  'peak_temp_c': 32,
  'peak_rh_pct': 80,
  'climate_note': 'Warm, humid hill climate'},
 {'state': 'Sikkim',
  'city': 'Gangtok',
  'lat': 27.338,
  'lon': 88.612,
  'peak_temp_c': 24,
  'peak_rh_pct': 80,
  'climate_note': 'Cool, very humid hill climate'},
 {'state': 'Chandigarh',
  'city': 'Chandigarh',
  'lat': 30.733,
  'lon': 76.779,
  'peak_temp_c': 40,
  'peak_rh_pct': 40,
  'climate_note': 'Hot summer, cold winter'},
 {'state': 'Puducherry',
  'city': 'Puducherry',
  'lat': 11.941,
  'lon': 79.808,
  'peak_temp_c': 37,
  'peak_rh_pct': 75,
  'climate_note': 'Coastal, hot & humid'},
 {'state': 'Andaman & Nicobar',
  'city': 'Port Blair',
  'lat': 11.667,
  'lon': 92.736,
  'peak_temp_c': 31,
  'peak_rh_pct': 80,
  'climate_note': 'Tropical island, very humid'}]
